### ISSUE TITLE
Air-Strafing/Bhopping

### ISSUE THREAD

**Issue by jumper-cable-morty** [0xspig/3dCharacterController#2]
This isn't really that much of an issue, but more of a question. I've been fiddling around with the variables a bit and trying out the controller, but I was wondering if there's a max speed or acceleration specifically in air separate from being on the ground. When I was bhopping with it I didn't seem to build up much speed.

**Comment by 0xspig** [comment]
There was in an older version but I think I took it out when I was testing all the slope stuff. Thanks for reminding me to put it back in. If you don't want to wait on me, my implementation was pretty simple. Add a variable called boost, have it accumulate while air strafing, set to 1 when not, then multiply velocity by boost when calling move_and_collide. I think you could also apply the boost during the airstrafe calculations so it doesn't affect vertical speed.

**Comment by 0xspig** [comment]
I've added speed accumulation to airstrafing in the latest commit. There are two new exports, one to set air acceleration and one to set the max air speed.
