### ISSUE TITLE
Mouse doesn't rotate the camera

### ISSUE THREAD

**Issue by EmeraldEelEntertainment** [0xspig/3dCharacterController#4]
I set a scene up for the character controller, set the inputs and tested the scene. The cursor is not centred and the mouse doesn't rotate the camera when moved around until I press the exit key.

EDIT: I know why the cursor is offset. It's because the window size hadn't been set to 1280 x 720 in the Project settings.

**Comment by 0xspig** [comment]
1. If you want to use a different resolution you should be able to resize the crosshair ColorRect.
2. Pressing "ui_cancel" (esc by default) toggles mouse capture. I've updated it to initialize as captured now.
